name: Dopamine
options:
  bundleIdPrefix: com.fake
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true

settings:
  base:
    CODE_SIGN_IDENTITY: ""
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGNING_ALLOWED: NO
    ENABLE_BITCODE: NO
    TARGETED_DEVICE_FAMILY: "1,2"

targets:
  Dopamine:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Dopamine
    info:
      path: Dopamine/Info.plist
      properties:
        CFBundleDisplayName: Dopamine
        CFBundleShortVersionString: "2.0.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIStatusBarStyle: UIStatusBarStyleLightContent
    entitlements:
      path: Dopamine/Dopamine.entitlements
      properties: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.fake.dopaminevisual
        PRODUCT_NAME: Dopamine
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
        FRAMEWORK_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Frameworks"
        HEADER_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Frameworks/Preferences.framework/Headers"
        OTHER_LDFLAGS:
          - "-F$(PROJECT_DIR)/Frameworks"
          - "-framework"
          - "Preferences"
